fragment PostFragment on Post {
  excerpt
  content
  title
  slug
  createdAt
  publishedAt
  seo {
    metaTitle
    metaDescription
  }
  author {
    data {
      attributes {
        name
        profile_image {
          data {
            attributes {
              url
              formats
            }
          }
        }
      }
    }
  }
  featured_image {
    data {
      attributes {
        url
        formats
      }
    }
  }
  primary_category {
    data {
      attributes {
        name
      }
    }
  }
  categories {
    data {
      attributes {
        name
      }
    }
  }
}
