query getCommentsByPost($post: String!) {
  findAllInHierarchy(relation: $post, filters: { blocked: { eq: false } }) {
    id
    blocked
    content
    createdAt
    author {
      name
      email
      avatar
    }
    children {
      id
      blocked
      content
      createdAt
      author {
        name
        email
        avatar
      }
    }
  }
}
