query getCommentsByPost($post: String!) {
  findAllInHierarchy(relation: $post, filters: { blocked: { eq: false } }) {
    blocked
    content
    author {
      name
      email
      avatar
    }
  }
}
