query pages($slug: String) {
  pages(filters: { meta: { slug: { eq: $slug } } }) {
    data {
      id
      attributes {
        title
        content
        meta {
          meta_title
          meta_description
          slug
        }
      }
    }
  }
}
