#import "../fragments/post.gql"

query posts($locale: I18NLocaleCode, $page: Int!, $pageSize: Int!) {
  posts(locale: $locale, pagination: { page: $page, pageSize: $pageSize }) {
    meta {
      pagination {
        total
        pageCount
      }
    }
    data {
      id
      attributes {
        ...PostFragment
      }
    }
  }
}
